INSERT INTO CVECategory (code, description) VALUES ('DoS',	'Denial of Service');
INSERT INTO CVECategory (code, description) VALUES ('EoBC',	'Execution of Binary code');
INSERT INTO CVECategory (code, description) VALUES ('DT',	'Directory traversal');
INSERT INTO CVECategory (code, description) VALUES ('XSS',	'Cross-site scripting');
INSERT INTO CVECategory (code, description) VALUES ('UDI',	'unauthorized disclosure of information');
INSERT INTO CVECategory (code, description) VALUES ('UM',	'unauthorized modification');
INSERT INTO CVECategory (code, description) VALUES ('UA',	'Unauthorized access');
INSERT INTO CVECategory (code, description) VALUES ('ML',	'Memory leak');
INSERT INTO CVECategory (code, description) VALUES ('BO',	'Buffer Overflow');
INSERT INTO CVECategory (code, description) VALUES ('Segfault',	'Segmentation fault');
INSERT INTO CVECategory (code, description) VALUES ('Bypass',	'bypass intended access restrictions');
INSERT INTO CVECategory (code, description) VALUES ('EAC',	'Execution of Arbitrary Code');
INSERT INTO CVECategory (code, description) VALUES ('GPF',	'General Protection Fault');
INSERT INTO CVECategory (code, description) VALUES ('UAA',	'User Acount Access');
INSERT INTO CVECategory (code, description) VALUES ('IO',	'Integer Overflow');
INSERT INTO CVECategory (code, description) VALUES ('SMC',	'Stack/Memory consumption');
INSERT INTO CVECategory (code, description) VALUES ('ITH',	'Improper Thread Handling');
INSERT INTO CVECategory (code, description) VALUES ('IEH',	'Improper Error Handling');
INSERT INTO CVECategory (code, description) VALUES ('ICI',	'Illegal Character Ingection');
INSERT INTO CVECategory (code, description) VALUES ('CSRF',	'Cross-site request forgery');
INSERT INTO CVECategory (code, description) VALUES ('ISH',	'Improper Session Handling');
INSERT INTO CVECategory (code, description) VALUES ('ICH',	'Improper Connection Handling');